### ISSUE TITLE
scoring api request body에 문제가 무엇인지도 전달 필요

### ISSUE THREAD

**Issue by hou27** [GUESS-ME-GDSC/Android#55]
## Description 👀
chat gpt를 사용하여 문제를 채점하면서
[scoring api 기능 명세서](https://www.notion.so/scoring-363d90a3fa2e4b37af5377bedf1f8cd5?pvs=4)
위 api에 문제가 무엇인지(key 값)도 함께 보내줘야 채점이 가능할 것 같습니다!

## Progress 🏃‍♀️
- [x]  scoring api request body에 'infoKey'라는 이름의 property로 문제도 함께 넘겨주실 수 있나요?

@915dbfl 

https://github.com/GUESS-ME-GDSC/Server/issues/71

**Comment by 915dbfl** [comment]
넵! 가능합니다!!

**Comment by hou27** [comment]
저번 회의 이후 최종 변경된 request body입니다

```java
public class ScoreReqDto {
    private String infoKey;
    private String infoValue;
    private Long personId;
    private MultipartFile image;
}
```
